application:
    title: "OTUS Spring course's application"
    version: 0.1
    locale: en

quiz:
  config:
    answer:
      shuffle: true
    question:
      shuffle: true
      count: 3
      succeed-percentage: 75
    path: classpath:quiz
    filename: quiz.yml